blog/tags/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from blog.models import Article,  Tag

tag = Blueprint('tag', __name__, url_prefix='/tags', static_folder='../static')


@tag.route('/')
def tag_list():
    tags: Tag = Tag.query.all()
    return render_template(
        'tags/list.html',
        tags=tags,
    )


@tag.route('/<int:pk>')
def tag_details(pk: int):
    selected_tag = Tag.query.filter_by(id=pk).one_or_none()
    if not selected_tag:
        raise NotFound(f"Tag #{pk} doesn't exist!")

    return render_template(
        'tags/details.html',
        tag=selected_tag,
    )

blog/templates/tags/details.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block body %}
    <div class="row">
        <h1>Тег: {{ tag.name }}</h1>
    </div>
    <div class="row">
        <div class="col-6">
            <h3> Articles: </h3>
            <ol>
                {% for article in tag.articles %}
                    <li><div><small class="text-muted">{{ article.title }}</small></div></li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}

blog/templates/tags/list.html
{% extends 'base.html' %}

{% block title %}
    Tags list
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Tags : </h1>

                    {% for tag in tags %}
                        <div class="col-6">
                            <div class="card h-100">
                                <div class="card-body">
                                    <a href="{{url_for('tag.tag_details',pk=tag.id)}}">
                                        <span class="badge text-bg-primary">{{ tag.name }}</span>
                                    </a>
                                    <div class="card-footer">
                                        <small class="text-muted">Articles</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
        </div>
    </div>
{% endblock %}