blog/author/views.py
from flask import Blueprint, render_template, redirect, request
from blog.models import Author

author = Blueprint('author', __name__, url_prefix='/author', static_folder='../static')

@author.route('/')
def author_list():

    authors = Author.query.all()
    return render_template(
        'authors/list.html',
        authors=authors,
    )

blog/report/views.py
from flask import Blueprint, render_template, redirect

report = Blueprint('report', __name__, url_prefix='/reports', static_folder='../static')

REPORTS = {
    1: 'Base report',
    2: 'Report for marketplace',
    3:  'Report for CRM',
}

@report.route('/')
def report_list():
    return render_template(
        'reports/list.html',
        reports=REPORTS,
    )

@report.route('/<int:pk>')
def get_report(pk: int):
    try:
        report_name = REPORTS[pk]
    except KeyError:
        # raise NotFound(f'Report id {pk} not found')
        return redirect(
            '/reports/'
        )

    return  render_template(
        'reports/details.html',
        report_name = report_name,
    )

blog/tags/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from blog.models import Article,  Tag

tag = Blueprint('tag', __name__, url_prefix='/tags', static_folder='../static')


@tag.route('/')
def tag_list():
    tags: Tag = Tag.query.all()
    return render_template(
        'tags/list.html',
        tags=tags,
    )


@tag.route('/<int:pk>')
def tag_details(pk: int):
    selected_tag = Tag.query.filter_by(id=pk).one_or_none()
    if not selected_tag:
        raise NotFound(f"Tag #{pk} doesn't exist!")

    return render_template(
        'tags/details.html',
        tag=selected_tag,
    )

blog/user/views.py
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, current_user, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash
from blog.models import User
from blog.forms.user import UserRegisterForm
from blog.extensions import db


user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile', pk=current_user.id))
    
    form = UserRegisterForm(request.form)
    errors = []
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('email not uniq')
            return render_template('users/register.html',form=form)

    _user = User(
        email=form.email.data,
        first_name=form.first_name.data,
        last_name =form.last_name.data,
        password=generate_password_hash(form.password.data)
    )

    db.session.add(_user)
    try:
        db.session.Commit()
    except TypeError:
        errors.append('Some error')
    else:
       login_user(_user)

    return render_template(
        'users/register.html',
        form=form,
        errors=errors
    )
    


@user.route('/')
def user_list():

    users = User.query.all()
    return render_template(
        'users/list.html',
        users=users,
    )

@user.route('/<int:pk>')
@login_required
def profile(pk: int):
    selected_user = User.query.filter_by(id=pk).one_or_none()
    if not selected_user:
        raise NotFound(f"User #{pk} doesn't exist!")

    return render_template(
        'users/profile.html',
        user=selected_user,
    )

blog/templates/base.html
<!doctype html>
<html lang='en'>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    {% block css %}
    <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet">
    {% endblock%}

    <title>{% block title %}My app - {% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      {% block body %}{% endblock %}
    </div>


    {% block js %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{url_for('static',filename='js/bootstrap.bundle.min.js')}}"></script>
  </body>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>    -->
    {% endblock %}
  </body>
</html>

blog/templates/navbar.html
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('article.article_list')}}">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('tag.tag_list')}}">Tags</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  href="{{ url_for('user.user_list')}}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  href="{{ url_for('author.author_list')}}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('report.report_list')}}">Reports</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('article.create_article')}}">Create article</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout')}}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>